import { FlowEmail, SIGNOFF_ALERTS, cta, quote } from './types';

const H = 60;
const D = 24 * H;

/** Post-Purchase Flow / Trump Insider Welcome Flow — verbatim. Starts on a
 *  completed purchase. Email 6 goes out on BOTH day 6 and day 7 (per doc). */
export const POST_PURCHASE_FLOW: FlowEmail[] = [
  {
    id: 'p1',
    offsetMinutes: 5,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'You’re in… let’s get to work' },
      { subject: 'Welcome to Insider Alerts' },
      { subject: 'You’re now on the inside' },
      { subject: 'You just made the smartest investing move ever', preview: 'Here’s what comes next' },
      { subject: 'Let’s build something big together' },
    ],
    body: [
      'Welcome aboard {{FIRSTNAME}},',
      'I’m thrilled you took this step.',
      'You’re now part of a movement done watching from the sidelines…',
      'And are ready to jump on profitable insider opportunities from politicians, elites and more.',
      'From now on,',
      'You stand a chance to turn the tables and build wealth the way most Americans only dream of.',
      'As you’ve realized, you can’t get ahead by doing what everyone else is doing.',
      'You’ll be getting Insider email & SMS alerts you can act on in minutes.',
      'I’ll make sure I send reminders so you don’t miss out on anything.',
      'You’ll also receive my private Trump Insider Watchlist and market insights that the media will never share with you.',
      'Most importantly, you have access to my “Legal Inside Tip” System, <strong>LIT.</strong>',
      'Every signal from <strong>LIT</strong> is based on legal insider trading.',
      'LIT taps into factors that determine quality insider moves.',
      'And as I promised,',
      'I’ll never throw insider trades at you without showing you steps to take.',
      'And while investing is risky…',
      'If a trade ever goes south, I won’t hide under my desk and I mean that.',
      `<p>As part of joining this movement, here’s your FREE report: ${cta('read it right here')}</p>`,
      'Take your time and read through. This is only the beginning of bright journey together.',
      'And if you have feedback for me, drop me a line at <a href="mailto:devs@insiderbuying.com" style="color:#e02b2b;">devs@insiderbuying.com</a>',
      'Together, we’ll build something big.',
      'Now you’re on the inside,',
      '__SIGNOFF__',
      'P.S.: I have a confession and it’s personal. It’s why I started this movement in the first place and the plans I have for you so you could hit your retirement goals. Stayed tuned',
    ],
  },
  {
    id: 'p2',
    offsetMinutes: 1 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'Why I started The Insider Alerts' },
      { subject: 'The moment everything changed for me' },
      { subject: 'My mission with Insider Alerts' },
      { subject: 'Here’s what made me build this' },
      { subject: 'I have a confession… and it’s personal' },
      { subject: 'My mission with this movement' },
      { subject: 'I took this lesson to heart.' },
    ],
    body: [
      '<p><strong>Hello, it’s George.</strong></p>',
      'Welcome again to this movement.',
      'I wanted to talk with you about my mission with <strong><em>Insider</em> Alerts</strong> and give you more clarity on how I could help you reach your goals.',
      'My mission is simple:',
      '<p><strong>I want to help you profit from the best insider moves from billionaires, members of Congress and more.</strong></p>',
      'That way, no matter what happens in the economy… your retirement stays rock solid…',
      'And you could win in this rigged system.',
      'I never stop looking for new ideas for you.',
      'And I know this might sound like one of those smooth-talking guys at the car dealership trying to upsell you on rust-proofing you don’t need…',
      'But that’s not me,',
      'I’m as regular a guy as you’ll ever meet.',
      'I’m not a practising Christian…',
      'But I was raised catholic and I believe in God. I didn’t get an “elite education” at any Ivy League school.',
      'I didn’t grow up around money, my parents never owned or talked about stocks while I was growing up.',
      'I only heard about them from a friend’s father…',
      'He was a stockbroker and managed money for wealthy families.',
      'He owned Ferraris, a massive home, a few vacation homes, and managed to put his 5 children into private school.',
      'I liked his lifestyle. I wanted to provide the same for my kids.',
      'That very night when I got home, I started reading stocks and was instantly hooked. It just made sense to me.',
      'From that day onward, the stock market interested me.',
      'And for a while…',
      'I thought I had it all figured out in the stock market… till everything fell apart.',
      '<p><strong><em>“How could I let this happen?”</em></strong></p>',
      'I uttered in disbelief as I stared at my brokerage account.',
      'I thought I had just found the world’s most undervalued stock.',
      'Little did I know… I was buying it at the top, and INSIDERS were dumping shares. I was buying the shares they were selling!',
      'I was their “exit liquidity.”',
      'I lost so much, I couldn’t afford lunch and had to rely on my parents for a while.',
      'That loss taught me the most important lesson of my career…',
      '<p><em><u>Follow the insiders, the people who actually know what’s going on behind the scenes.</u></em></p>',
      'And I believe with every ounce of passion my body:',
      '<p><strong>Today, as you read this… is the absolute best time in all of human history to be alive.</strong></p>',
      'Forget the mainstream media narratives.',
      'Of course, America and the world face huge problems.',
      'But it’s the problems that lead to breakthroughs…',
      'And breakthroughs create more wealth and more opportunity, which leads to more wealth.',
      'I hope that makes sense.',
      'And like I said, we are in this together.',
      'Now you’re on the inside,',
      '__SIGNOFF__',
      'P.S.: While I can’t reply to emails… I’m curious, have you gone through the report? What did you like the most about it?',
      'P.P.S: We’ve all faced serious problems in our lives. I know my story isn’t unique. I know you have a story, too.',
      'If you feel comfortable, I’d love to hear your story of overcoming adversity to get to where you are today. You can simply reply to this email and share your story.',
      'Don’t worry, whatever you write will remain private and confidential. Thanks!',
    ],
  },
  {
    id: 'p3',
    offsetMinutes: 2 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'I will never break this promise to you' },
      { subject: 'Here’s my promise to you' },
      { subject: 'I’ll keep this promise to you' },
      { subject: 'My promise to you… And I’ll keep it' },
      { subject: 'You have my word…' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'Today, I’m going to make you an ironclad promise.',
      'This promise is an unbreakable bond between us.',
      'I want one of the vast new fortunes created by legal insider buying in the years ahead to be yours.',
      'I want that money in your account. For you to use as you please.',
      'I want you to sit at the dinner table with your family… feeling proud you have the basics covered.',
      'That’s my ironclad promise to you: I will always put you, your goals, your dreams, and your success first. That’s why I do what I do.',
      'I will never stop working for you… to show you more insider buying trends you can act on and make money.',
      'Like I said, I didn’t come from money.',
      'But today, I get to travel, write, talk to amazingly smart people, and then write to you about how to invest in the best ideas I or LIT finds.',
      'And we’ll talk more soon about my best ideas of the moment.',
      'As the saying goes, it’s the hottest fires that make the hardest steel.',
      'That’s why you can take my promise to you right to the bank.',
      'I do what I say, and I say what I mean.',
      'Now here’s my ironclad promise to you one more time: I will always put you, your goals, your dreams, and your success first. That’s why I do what I do.',
      'I am determined to show you how to radically increase your wealth. More on that tomorrow',
      'Now you’re on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'p4',
    offsetMinutes: 3 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'One year changed my life, it could change yours too' },
      { subject: 'One year changed my life… here’s how it could change yours too' },
      { subject: 'Can one year change your life?' },
      { subject: 'Here’s what one year could do to your life' },
      { subject: 'Do you believe one year can change your life?' },
    ],
    body: [
      'Dear {{FIRSTNAME}},',
      'Can you change everything about your life in one year?',
      'Yes, you could. I am living proof.',
      'Remember when I told you I was on the wrong side of a trade?',
      'When insiders were dumping their stock holdings?',
      'I don’t talk about it much, but I invested my life savings.',
      'Talk about going from 100 to 0 real quick.',
      'I still remember how I felt that day, some tears rolled down my face.',
      'I had gone from “the top of the mountain” to being another victim of the wrong side of the trade…',
      'I’m sure you can relate to that feeling.',
      'This experience taught me it’s important to know WHO the insiders are in a company,',
      'WHAT they are doing (buying or selling),',
      'And if they are in it for the long run to create shareholder value or just looking to fatten their own pockets.',
      'Fast forward to 7 years later,',
      'I was consulting for a little-known mining company and received stock options at $5.',
      'From the outside, this company looked like a sinking ship. Operations were shaky and most people had written it off.',
      'I could have sold everything off…',
      'But I knew who the real players were. I had a front-row seat to what the insiders were planning.',
      'I couldn’t trade with this information or tell anyone, that’d have been illegal.',
      'A few months later, the stock broke $7. I remember seriously considering selling all of my shares for a very nice return.',
      'But with what I knew… I decided to hold on longer.',
      'What followed was just an insane ride. The stock went on to break $70… on paper, my shares were worth $5.2 million.',
      'And by the time I sold, I had cleared $3 million. My parents thought I had robbed a bank. In some ways… It felt like I did.',
      'This didn’t happen because I gambled or followed the media’s narrative…',
      '<p><strong>But because I knew what the insiders were doing.</strong></p>',
      'And if anyone followed these same principles…',
      'They could have earned…',
      '<p><strong>1382% returns on Kulr Technologies Group (Ticker: KULR)</strong></p>',
      '2,063% returns on SilverCrest Metals (Ticker: SILV)...',
      '<p><strong>And 2847% on Emerita Resources (Ticker: EMO)</strong></p>',
      '$1,000 into these trades would have earned you a profit of $6,100.',
      'A secure retirement is possible when you follow the money, the right way.',
      'One year could change everything.',
      'That’s why I can say with 100% conviction…',
      'No matter what hardships you’ve been through, no matter what you think is holding you back… you CAN change your life and reach your goals.',
      'Now you’re on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'p5',
    offsetMinutes: 4 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'Why the elites don’t want you to have this' },
      { subject: 'The system isn’t broken. It’s built this way.' },
      { subject: 'This is why regular investors never win' },
      { subject: 'What we’re up against (and how we will beat it)' },
      { subject: 'Here’s how everyday folks can beat the rigged system' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'The system’s not broken… It\'s rigged.',
      'The financial elites know how to move first.',
      'The legacy media know how to spin the stories to their narrative.',
      'And while there is good information and quality investing ideas out there…',
      'The problem is, it’s increasingly hard to find. It’s like trying to find a diamond in piles of landfill garbage.',
      'One columnist says one thing about a stock or an industry.',
      'A talking head on TV says the opposite.',
      'A trader with a Twitter account says something else… which gets picked up and runs in a business publication like Barron’s or The Wall Street Journal.',
      'Meanwhile, the stock goes up… or down… or both.',
      'Where’s the truth?',
      'That’s a problem for regular folks like you and me.',
      'You and I have been left holding the bag too many times.',
      'You get the headlines <em>after</em> the move’s already happened.',
      'And we\'re supposed to be okay with that?',
      'That’s what we’re up against. But that’s also why I started this movement.',
      'Because once you know where the insiders are putting their money and why… you’ve all of a sudden flipped the script.',
      'You’re no longer playing catch-up.',
      'You know the trades to get in on for potential profits and the trades to stay away from… helping protect and grow your wealth ahead of retirement.',
      'Together, we’ll be tracking quality insider moves… because that’s where the next wave is building.',
      'Now you’re on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'p6a',
    offsetMinutes: 5 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'New member opportunity!' },
      { subject: 'Attention: new member opportunity!' },
      { subject: 'Here’s a new opportunity for you' },
      { subject: 'This new opportunity is for you' },
      { subject: 'New opportunity waiting for you inside' },
    ],
    body: UPSELL_BODY(),
  },
  {
    id: 'p6b',
    offsetMinutes: 6 * D,
    brand: 'INSIDER ALERTS',
    signoffTitle: SIGNOFF_ALERTS,
    subjects: [
      { subject: 'New member opportunity!' },
      { subject: 'Attention: new member opportunity!' },
      { subject: 'Here’s a new opportunity for you' },
      { subject: 'This new opportunity is for you' },
      { subject: 'New opportunity waiting for you inside' },
    ],
    body: UPSELL_BODY(),
  },
];

/** Email 6 body (sent on days 6 & 7) — verbatim. */
function UPSELL_BODY(): string[] {
  return [
    'Hello {{FIRSTNAME}},',
    'As I’ve explained to you…',
    'Now is a great time to be alive.',
    'From how we interact with our loved ones and the world, work, travel, and many more.',
    'Think back to the horse and buggy days…with all the industrial revolutions in between… to this very moment.',
    'We’ve come a long way…',
    'And creating untold wealth in the process.',
    'And despite all the negative narrative from the legacy media…',
    'There’s a TON of money to be made from following the right money moves.',
    'And if you know how to play the game now… before the rest of the herd catches on…',
    'You stand to win big for your loved ones in the coming months and years.',
    'And we’re in this together. I’ll be guiding you with up-to-the-minute profit opportunities from trump insiders.',
    'Over the next decade,',
    'Trillions of dollars are going to be made thanks to new opportunities.',
    'That’s why it’s critical you have access to this movement for the long term…',
    'So for the next 48 hours only…',
    'I’m going to extend my offer to you to become an Elite Lifetime member of <strong>Insider Alerts</strong>',
    '<p><strong>Take this simple step today…</strong></p>',
    '<p><strong>And you’ll be an elite lifetime member… for life.</strong></p>',
    'However, I have to let you know: This premium is available for the next 49 hours.',
    'And when it’s up, that’s it…',
    'So please do this now, while you still have time.',
    `<p>${cta('Click here NOW to upgrade to your Elite Lifetime membership today.')}</p>`,
    'As soon as you do, you’ll get access to every member benefit, my research and every hand-picked insider play to help you profit… <strong>for life!</strong>',
    '<p style="text-align:center;font-size:19px;"><strong>Unlimited Access to Everything – FREE for LIFE</strong></p>',
    'After you upgrade today… your new <strong><em>Insider Alerts</em></strong> subscription is effectively FREE for life.',
    'You’ll NEVER see another subscription fee ever again…',
    'If I ever raise the price of the regular annual subscription price',
    'Or if publishing costs go up…',
    'Or I add bonus features (which could increase the total value of your subscription)...',
    'No matter what happens…',
    '<p><strong>You won’t have to pay a dime.</strong></p>',
    'Again, now is the time to buckle up and follow the best and under-the-radar insider moves…',
    'By securing your upgrade today, you’ll be on the inside… and will save a fortune in unnecessary annual fees.',
    'Don’t forget you’ll also get…',
    '<p style="text-align:center;font-size:19px;"><strong>Access to the Elite <em>Insider Alerts</em> “Legacy Program”</strong></p>',
    'This is a big one…',
    'And you will hardly get this anywhere else.',
    'You see…',
    'You and your loved ones must get my research when you need it.',
    'That’s why I created the <strong><em>Insider Alerts</em></strong> “Legacy Program.”',
    'It allows you to pass your subscription to a loved one at ANY time.',
    '<p><strong>That means anyone you decide could always get access to the <em>Insider Alerts</em>…</strong></p>',
    '<p><strong>And profit from any insider opportunity and build wealth.</strong></p>',
    'You won’t get this level of benefits anywhere else.',
    'They’re only part of our Elite Lifetime membership…',
    'But there is one catch…',
    '<p style="text-align:center;font-size:17px;"><strong>This Membership Deal is Only Available for The 99 New Subscribers Today</strong></p>',
    'As you know, I put in a lot of effort to serve you with the best in this movement.',
    'It’s all about a secure retirement…',
    'So you don’t have to look at your wife and ever say about the basics, <em>“Honey, we can’t afford that.”</em>',
    '<p><strong>So this is on a first-come, first-served basis.</strong></p>',
    'And once the 99 upgrades come in…',
    'You probably won’t get this chance again',
    'I understand this will not be right for everyone…',
    'I’m only looking for those who are serious about taking advantage of quality insider moves.',
    'Those who understand the market is rigged and want to flip the script on the elites',
    '<p><strong>And this deal is designed to help you profit for <em>years</em> to come… no matter what happens.</strong></p>',
    `<p>${cta('Here’s your way in')}</p>`,
    'The level of service for this lifetime offer is invaluable.',
    'As a brand-new subscriber, you saw I offered you $399 for this elite upgrade.',
    'Of course, I understand if you weren’t ready to take me up on that offer at the time.',
    'But I wouldn’t be looking out for you if I didn’t give you another chance to get the best deal on your subscription…',
    'That’s why today…',
    'As an added show of good faith, I’m going to extend my offer on this elite Lifetime membership one last time…',
    'After you upgrade,',
    'Your <strong><em>Insider Alerts</em></strong> subscription is effectively FREE for life!',
    'Plus, it still comes with everything I’ve laid out for you today…',
    'But you need act fast.',
    'I suspect all 99 spots could fill up <em><u>before</u></em> the 48-hour deadline.',
    'So click the secure link below now, while it\'s still fresh in your mind…',
    `<p style="text-align:center;">${cta('<strong>YES! UPGRADE MY MEMBERSHIP TODAY</strong>')}</p>`,
    'I’m confident you’ll want to keep this research coming year after year…',
    'All you need to do to accept my offer and secure a lifetime of research is click the link below.',
    `<p style="text-align:center;">${cta('<strong>YES! UPGRADE MY MEMBERSHIP TODAY</strong>')}</p>`,
    'Now you’re on the inside,',
    '__SIGNOFF__',
  ];
}
