import { FlowEmail, SIGNOFF_BUYING, cta, quote } from './types';

const H = 60;
const D = 24 * H;
/** The welcome flow "ends" at day 10 (240h). The urgency emails count down
 *  to that deadline, exactly as the doc times them: Day 9 = 24 hours left,
 *  then 16h, 12h, 2h, 1h and 10 minutes left. */
const END = 10 * D;

/** Urgency Flow (Day 9, 24 hours to the end of Welcome Flow) — verbatim. */
export const URGENCY_FLOW: FlowEmail[] = [
  {
    id: 'u1',
    offsetMinutes: END - 24 * H,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Please… don’t panic', preview: 'There’s hope…' },
      { subject: 'The stock market might be unstable', preview: 'just breathe' },
      { subject: 'Don’t panic about the stock market', preview: 'This stock could double before the media catches on' },
      { subject: 'The real opportunity isn’t crypto or gold… It’s this $13 stock', preview: 'Insiders are quietly buying one Trump-connected stock. Here’s why' },
      { subject: 'Please… don’t panic about the stock market', preview: 'There’s hope…' },
    ],
    body: [
      '<p><strong>Hello {{FIRSTNAME}},</strong></p>',
      'Forget the legacy media narratives.',
      'I know this is one of the most uncertain periods in stock market history.',
      'The Wall Street Journal reported the Dow was on track for its worst April since 1932, the bottom of the Great Depression.',
      'Then suddenly, the market bounced back.',
      'If you’re feeling unsure about where to turn… you’re not alone.',
      'But in moments like this, <strong>there’s always a signal buried in the noise</strong>.',
      'And if you follow the money, you could watch your net worth soar in months to come',
      `<p>${cta('Click here to gain access to LIT')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'u2',
    offsetMinutes: END - 16 * H,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Here’s how much you need to retire' },
      { subject: 'Do you know how much you need to retire?' },
      { subject: 'Northwestern Mutual says you need this to retire' },
      { subject: 'Cantor Fitzgerald projects this stock will double in months' },
      { subject: 'The average American needs this to retire' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'Northwestern Mutual now says the average American needs $1.26 million to retire comfortably. Back in the day, folks retired on half that.',
      'Social Security is drying up with waste and fraud as Elon Musk revealed.',
      'America is over $36 trillion in debt.',
      'And the stock market is getting more unpredictable by the day.',
      `<p>If you are going to retire as you desire, ${cta('you’ll need an edge.')}</p>`,
      'In the next few minutes, you could be one of the few Americans with inside information…',
      `<p>${cta('Here’s how you can gain access')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'u3',
    offsetMinutes: END - 12 * H,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Warren Buffett said it best…', preview: 'And you could use it to build your family legacy' },
      { subject: 'The best time to buy is when fear is high', preview: 'And that’s right now' },
      { subject: 'What would Buffett do right now?', preview: 'And what you should do too' },
      { subject: 'This quote explains exactly what’s happening today', preview: 'And how you could hand you more vacations' },
      { subject: 'Use the rule the smart money lives by', preview: 'And you could get more vacations with family' },
    ],
    body: [
      '<p><strong>Hello {{FIRSTNAME}},</strong></p>',
      '<p><strong>Warren Buffett once said:</strong></p>',
      quote('“Be fearful when others are greedy. Be greedy when others are fearful.”'),
      'Right now, the media and elites are playing the same old script, pushing fear down throats.',
      `<p>But now’s a great time to position for potential profit rides … ${cta('if you follow the right money moves.')}</p>`,
      'While no one really knows where the market\'s headed…',
      'Following the right money moves could hand anyone an edge over Main Street Investors.',
      `<p>${cta('Click here to join the ride')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'u5',
    offsetMinutes: END - 2 * H,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Here’s what you’re getting from this alert' },
      { subject: 'LIT: Get access to me and profit from quality insider moves' },
      { subject: 'Hey {{FIRSTNAME}}, this is yours' },
      { subject: 'Do you have the courage to profit from this insider access?' },
      { subject: 'Get full access to LIT and profit from the best insider moves' },
    ],
    body: [
      'Hi {{FIRSTNAME}},',
      `<p>Here’s what you’ll get when ${cta('you join <strong><em>Insider Alerts</em></strong> in the next few minutes:')}</p>`,
      '✔️ Alerts based on real insider trades from billionaires, politicians and elites',
      '✔️ <strong>Access to LIT</strong>',
      `<p>✔️ ${cta('And many more you can see right here')}</p>`,
      `<p>As I’ve shown you since you joined this movement, ${cta('all you have to do is follow the money.')}</p>`,
      'That way, you could grow and protect your wealth ahead of retirement… no matter what’s going on in the market.',
      'And without crossing your fingers and hoping the market “cooperates.”',
      'You also get to plan more vacations and spend quality time with family… or anything you decide to do in the future.',
      'And if you decide to do nothing, it’s okay too… but watching from the sidelines is never fun.',
      `<p>${cta('Which side will you be on?')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'u6',
    offsetMinutes: END - 1 * H,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Your neighbor might hear about it next week' },
      { subject: 'How would you feel if your neighbor told you about their loss?' },
      { subject: 'Do you want your neighbor to tell you about this instead?' },
      { subject: 'You’re either in… or you’re watching from the sidelines' },
    ],
    body: [
      '<p><strong>Hello {{FIRSTNAME}},</strong></p>',
      '<p><strong>Imagine this for a moment:</strong></p>',
      'You’re with your friends, neighbors or golf buddies…',
      'And one of them starts going off about a stock you’ve had in your portfolio for months.',
      quote('“Did you hear what happened with that stock? It’s been on a run these past months… I just got in yesterday.”'),
      quote('Another confesses, “Yeah, I just saw it on CNBC, wish I heard about it earlier.”'),
      'You’ll smile. Maybe say nothing.',
      'But deep down, you’ll know… You saw it before they did and you made the call.',
      `<p>Now I’m not saying ${cta('you will get all the perfect stock moves with LIT')}</p>`,
      'There’s no black box system in the stock market.',
      'But while the media won’t relent on distracting Americans with endless drama…',
      'You could stop feeling like you missed the boat… follow the money without sweating it…',
      'And secure your retirement.',
      `<p>${cta('Click here to see how you could get ahead of your neighbors and golf buddies')}</p>`,
      'See you on the inside.',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'u7',
    offsetMinutes: END - 10,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'It’s in your hands {{FIRSTNAME}}' },
      { subject: 'You’re in the driver’s seat {{FIRSTNAME}}' },
      { subject: 'One last thing {{FIRSTNAME}}…' },
      { subject: 'This is it {{FIRSTNAME}}' },
      { subject: 'It’s your call' },
      { subject: 'You’re in the driver’s seat' },
    ],
    body: [
      '<p><strong>Hello {{FIRSTNAME}},</strong></p>',
      'You can let the elite and the media pressure you to ” play it safe…”',
      'While you miss the opportunities that could hand you more freedom and quality time with your family.',
      'Their fear tactics only keep you stuck… and can’t help you build wealth.',
      'Or since you’re a part of this movement…',
      `<p>You could take the wheel with both your hands and ${cta('make moves with the smart money.')}</p>`,
      'You could walk away from your job without worrying if groceries or gas will wipe out your savings.',
      'While average investors will, as always, sit on the sidelines…',
      'Only a few will act today and reap the rewards… and that’s okay.',
      'Which side will you be on, {{FIRSTNAME}}?',
      'Whatever you decide… I’m rooting for you.',
      `<p>${cta('You’re in the driver’s seat.')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
];
