import { FlowEmail, SIGNOFF_BUYING, cta, quote, press } from './types';

const H = 60; // minutes per hour
const D = 24 * H; // minutes per day

/** Welcome Flow — emails 1–8, verbatim from the copy doc. */
export const WELCOME_FLOW: FlowEmail[] = [
  {
    id: 'w1',
    offsetMinutes: 5,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Welcome {{FIRSTNAME}} now you’re on the inside', preview: 'I have a secret to tell you' },
      { subject: 'This is how everyday Americans can get ahead', preview: 'Starting a few minutes from now' },
      { subject: 'Insiders are making moves. You’re about to know where', preview: 'And how you could profit' },
      { subject: 'Let’s beat the rigged stock market together', preview: 'Starting a few minutes from now' },
      { subject: 'Now you have the investing edge millions of Americans only dream of' },
      { subject: '“How could I let this happen?”', preview: 'I feel the pain to this day' },
      { subject: 'Welcome to the movement {{FIRSTNAME}}', preview: 'I have a secret to tell you' },
      { subject: 'I’m revealing a secret to you here', preview: 'Now you’re one of us.' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      '<p><strong><em>“How could I let this happen?”</em></strong></p>',
      'I uttered in disbelief as I stared at my brokerage account.',
      'I’d just lost all my savings investing in a stock on the back of hype from the media while insiders in the company were cashing out…',
      'I’ll tell you more about my story in a bit…',
      'But first,',
      'I’d like to welcome you to Insider Buying.',
      'If you still believe in the American dream…',
      'If you know the system is rigged to favor the elites...',
      'And if you believe,',
      'Despite the negative narrative flying around about the economy, America will get back to its peak…',
      'You’re in the right place.',
      'My name is George Aizpurua, and I’m the founder of this movement. I started it for one reason:',
      '<p><strong><em>To help everyday Americans legally profit from the <u>best</u> Insider and elite moves before the rest of the world catches on.</em></strong></p>',
      'That means you could profit from <strong>legal insider trading,</strong> unlike “America’s Best Trader,” Nancy Pelosi and most of Congress.',
      'And you could stop worrying you’ll have to work through retirement just to keep the lights on.',
      'Legendary investor Peter Lynch said it best,',
      '<p><strong><em>"Insiders might sell their shares for any number of reasons, but they buy them for only one… they think the price will rise."</em></strong></p>',
      'As you and I proceed on this journey together,',
      'You’ll be getting alerts when the right insiders start buying stocks quietly…',
      'Deep dives that show you what’s really going on in Washington, on Wall Street, and behind closed doors.',
      'You’ll also get clarity in a market flooded with the media’s fear-mongering.',
      'And I won’t just throw insider data at you, I’ll break down the smartest moves with real profit potential.',
      'So you could make better investment decisions…',
      'Help your kids and grandkids start out something real… and stay on track for retirement.',
      'No matter the market’s condition.',
      'My team has over 100 years of combined experience in investing and financial research.',
      'And with the American dream now worth $1.26 million…',
      'Following the right insiders could help you and me uncover market-moving trends before the rest of the world catches on.',
      'And I know you’re thinking right now…',
      quote('“The markets are unstable. The American dream is harder to achieve. Social Security will be gone in a few years. America’s debt keeps piling up”'),
      'I understand your concerns…',
      'But a comfortable retirement is possible without gambling your savings on options, meme coins or any other risky venture…',
      'If you have the right information.',
      'See you on the inside,',
      '__SIGNOFF__',
      'P.S.: Sorry, I didn’t get a chance to tell you how I lost all my savings today… I promise to spill everything in tomorrow’s email. Stay tuned…',
    ],
  },
  {
    id: 'w2',
    offsetMinutes: 1 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: '“How could I let this happen?”', preview: 'I feel the pain till this very moment.' },
      { subject: 'How I lost everything…', preview: 'And then made $3 million' },
      { subject: 'The moment everything changed for me', preview: 'And how it could change for you too' },
      { subject: 'From broke to beating the elites at their own game', preview: 'Here’s how you can flip the script' },
      { subject: 'Why I started the Insider Buying Movement', preview: 'I feel the pain to this very moment' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      '<p><strong><em>“How could I let this happen?”</em></strong></p>',
      'I uttered in disbelief as I stared at my brokerage account.',
      'I’d just lost all my savings in a stock on the back of hype from the media while insiders in the company were cashing out.',
      'Turns out I was providing exit liquidity to the elites who already made their move.',
      'You see,',
      'I didn’t grow up around money. We were like most folks… living paycheck-to-paycheck.',
      'My family never talked about or owned stocks, no one even knew how the market worked.',
      'Then I heard about stocks from a friend’s father…',
      'He was a stockbroker and managed money for wealthy families.',
      'He owned Ferraris, massive homes and put his 5 children into private school.',
      'I loved his lifestyle. I wanted my kids to get the best of out life.',
      'That very night when I got home, I started reading about stocks and was instantly hooked. It just made sense to me.',
      'From that day onward, the stock market interested me.',
      'But here I was years later, gutted from losing all my savings after blindly following the media.',
      'I thought I had found the world’s most undervalued stock.',
      'Little did I know… I was buying it at the top, and INSIDERS were dumping shares.',
      'I lost so much, I couldn’t afford lunch and had to rely on my parents for a while.',
      'That loss taught me the most important lesson of my career…',
      '<p><em><u>Follow the <strong>right</strong> insiders, the people who actually know what’s going on behind the scenes.</u></em></p>',
      'I took that lesson to heart.',
      '7 years later, I was consulting for a little-known mining company and received stock options at $5.',
      'From the outside, this company looked like a sinking ship. Operations were shaky and most people had written it off.',
      'But I knew who the real players were. I had a front-row seat to what the insiders were planning.',
      'In no time, the company’s stock soared past $70.',
      'And when I finally cashed out… I walked away with $3 million. My parents wouldn’t believe it, they felt I had just robbed a bank.',
      'Well, in many ways, it felt like I did.',
      'This didn’t happen because I gambled or blindly followed the media’s narrative…',
      '<p><strong>But because I knew what the <u>right</u> insiders were doing.</strong></p>',
      'Today, that’s exactly what I want to help regular folks do…',
      'I’m sure you’ve had a terrible experience in the stock market, too.',
      'That’s why you have to tune out all the noise…',
      'Follow the money the right way,',
      'Position for potential life-changing returns before the herd ever sees it coming and in the long run, secure your retirement.',
      'So you get to stop asking, <em>“Where did my money go?”</em> but instead, <em>“Where should I put it next?”</em>',
      'That’s why I started this movement.',
      'So you could make decisions based on facts, and not fear, hype or whatever the legacy media is spinning.',
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'w3',
    offsetMinutes: 2 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'What if retirement doesn’t go the way you planned?' },
      { subject: 'You know the market is rigged', preview: 'Here’s what you can do about it' },
      { subject: 'Stock Market: “I’m rigged to favor the elites.”', preview: 'Here’s what you can do about it' },
      { subject: 'The market might be rigged… but here’s a solution' },
      { subject: 'How do you plan retirement when the market’s rigged?', preview: 'This is the answer' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'Whether retirement’s right around the corner or already here…',
      'You might have this on your mind:',
      quote('“How do I protect what I’ve built… and make sure it lasts?”'),
      'You’ve worked hard and saved. But the market’s rigged.',
      'Studies show regular folks do much worse than the market averages.',
      press('Forbes', 'Why The Average Investor’s Investment Return Is So Low'),
      'Yet the financial elites have raked in steady profits year after year,',
      'Nancy Pelosi, together with some members of Congress have been reaping steady returns from the stock market.',
      'You and I know there’s a game going on behind the scenes… you’ve heard the stories about insider trading.',
      'CBS’ 60 Minutes reports House and Senate members’ stock portfolios performed better than the market average by 6% and 10%, respectively.',
      'Last year was no exception…',
      press('Fortune', 'Members of Congress again outperformed the stock market, report shows'),
      'They’re getting richer by the minute…',
      'But I’ll tell you this…',
      'You stand a chance to profit from legal insider trading…',
      'While the rest of Main Street investors stay in the dark.',
      'You could wake up and check your portfolio, not out of fear but with a quiet sense of confidence.',
      'You could follow the top insider trades without spending hours scanning through Form 4s, 13F filings or reading the news.',
      'Think of it as a secret “Legal Inside Tip”…',
      'More on this later…',
      'See you on the inside,',
      '__SIGNOFF__',
      'P.S.: How do you know what Insider trades to follow and those to avoid like the plague without spending hours scanning through Form 4s, 13F filings or reading the news? I’ll reveal my secret to you.',
      'Don’t miss the next email…',
    ],
  },
  {
    id: 'w4',
    offsetMinutes: 3 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: '“The legal trick” everyday Americans can quietly use' },
      { subject: 'This is how you can catch quality insider moves before the media does' },
      { subject: 'REVEALED: My ‘legal inside tip’ anyone can use' },
      { subject: 'This simple “legal inside tip” system could change how you invest' },
      { subject: 'Catch the next inside trade with my “legal inside tip”' },
      { subject: 'Here’s what my ‘legal inside tip’ just found' },
      { subject: 'Your retirement plans just got LIT up' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'Remember I told you how I made $3 million from a single stock?',
      'After spending 8,761 hours and 100s of thousands of dollars of my own money…',
      'I developed a proprietary system based on the same principles I used to profit from that trade.',
      `<p>${cta('I call it my “Legal Inside Tip” or LIT.')}</p>`,
      'LIT is a simple but powerful tool I fine-tune every time.',
      'It gives stocks an insider quality score, so we know exactly which ones deserve our attention..',
      'And those not to touch within a ten-foot pole.',
      'Think of LIT as your buddy with inside information, only you get it without breaking the law.',
      'That way, you could make money the way insiders and elites do by knowing what’s coming before it hits the headlines.',
      'You see,',
      'Not every insider trade matters…',
      'Like when a CEO or COO exercises cheap options, gets bonus shares, or purchases $10,000 of stock on any given day.',
      'These, in other words… are meaningless.',
      'And Investopedia agrees with me…',
      press('Investopedia', 'The significance of insider buying depends on the amount purchased, the timing, and the insider’s track record, not just the act itself.'),
      'LIT taps into these factors and gives trades with huge potential:',
      '<ul style="margin:12px 0 16px;padding-left:24px;">' +
        '<li style="margin:8px 0;">Insider purchase size compared to the market cap of the company. Here, LIT considers how big the insider’s buy is, compared to the whole company’s worth. The bigger, the better.</li>' +
        '<li style="margin:8px 0;">The number of insiders moving at once. If many insiders are buying at once, you have to pay attention.</li>' +
        '<li style="margin:8px 0;">Seniority of insiders buying ( CEOs, COOs, politicians and billionaires carry more weight than a junior worker)</li>' +
        '<li style="margin:8px 0;">Increase in current holdings of insiders.</li></ul>',
      'When it signals a buy, that’s when you and I strike.',
      'Following these factors helped me lock in $3 million.',
      'And anyone who used the same factors in following insider moves could have earned…',
      '<ul style="margin:12px 0 16px;padding-left:24px;">' +
        '<li style="margin:8px 0;"><strong>1382% returns on Kulr Technologies Group (Ticker: KULR)</strong></li>' +
        '<li style="margin:8px 0;">2,063% returns on SilverCrest Metals (Ticker: SILV)</li>' +
        '<li style="margin:8px 0;"><strong>And 2847% on Emerita Resources (Ticker: EMO)</strong></li></ul>',
      '$1,000 into these trades would have earned you $61,000.',
      'And what if you put in $10,000?',
      'You would have netted a $610,000 nest egg.',
      'That’s more than enough money to plan a vacation to spend more time with the family or pay the tuition of your kids or grandkids...',
      'And to sit down at the dinner table and feel proud of how you provide for the family.',
      'Of course…',
      'I also want you to know there’s no black box system in investing.',
      'It’s important you don’t invest more than you can afford to lose.',
      'All LIT does is it taps into those factors I mentioned to get quality insider buys,',
      'So that way… you won’t be gambling your hard-earned money in the stock market.',
      'You’ll be way ahead of the wave before it hits the mainstream media…',
      'And you could be way on track for retirement.',
      `<p>${cta('When you access LIT today,')} you’ll know exactly when to act and when to stay put.</p>`,
      `<p>${cta('Here’s how you can access LIT')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'w5',
    offsetMinutes: 4 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Imagine making this move before the media catches on', preview: 'You won’t believe how easy it is' },
      { subject: 'Think about this for a second {{FIRSTNAME}}', preview: 'Here’s how you could get ahead' },
      { subject: 'URGENT: Trump-connected insider move', preview: 'Here’s how you can get in' },
      { subject: 'Imagine this for a second…', preview: 'You could be up double digits while the media’s catching up' },
      { subject: 'Imagine this {{FIRSTNAME}}…', preview: 'You could be up double digits while the media’s catching up' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'Imagine this:',
      'You wake up, grab your coffee, and check your inbox.',
      'There it is… an alert showing what insiders just bought.',
      'You get in early. The stock pops.',
      'And while the legacy media’s still trying to catch up with the story…',
      'You’re already up double digits.',
      'This is no dream {{FIRSTNAME}}...',
      'That’s exactly what happened with SilverCrest Metals (SILV)… and anyone who held on to the trade could have earned a 2,063% windfall.',
      'Enough to turn $10,000 into a whopping $206,300.',
      'That would help arrange a vacation with the family at any location you desire.',
      'But it’s important you don’t invest more than you are willing to lose.',
      'There is no black box or perfect system in investing',
      `<p>${cta('but right now, there’s an opportunity')}.</p>`,
      'In the next few minutes… I’m going to give you access to LIT',
      'FOR FREE',
      `<p>${cta('Click here to see why and how you can gain access')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'w6',
    offsetMinutes: 5 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Harvard, Elon, and Icahn all agree on this', preview: 'And it could hand you more freedom' },
      { subject: 'The smartest money in America does this', preview: 'And it could land you more freedom' },
      { subject: 'What Dimon, Icahn & Musk did to quietly profit…', preview: 'And how you could use it legally' },
      { subject: 'Beat the S&P by double digits?', preview: 'Here’s how you could use it today' },
      { subject: 'Do you have the courage to beat the market by double digits?', preview: 'Here’s what I mean…' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'A Harvard study found that legal insider buying beat the market by double digits every year.',
      'Even Investopedia reports:',
      press('Investopedia', 'if executives, directors, or others with inside knowledge of a public company are buying or selling shares, investors should consider doing the same thing.'),
      'And to top it all,',
      'Seeking Alpha revealed the five Dow Jones members with the highest insider ownership stakes…',
      'Created higher total returns for investors over the last ten years…',
      'Compared with those with lower insider ownership',
      'And by following the money, you could have found out:',
      '<ul style="margin:12px 0 16px;padding-left:24px;">' +
        '<li style="margin:8px 0;"><strong>Carl Icahn sold off his steel stock holdings in 2017 before Trump’s steel and aluminium tariffs…</strong><br>Netting $31 million in the process</li>' +
        '<li style="margin:8px 0;">Elon Musk bought millions in Tesla stock in 2018 … weeks before a massive rally.</li>' +
        '<li style="margin:8px 0;"><strong>JP Morgan CEO Jamie Dimon bought 500,000 bank shares near the bottom of the 2016 steep stock slide…</strong><br>Before it soared weeks later.</li></ul>',
      'This happens all the time... every week.',
      'But most Americans never see it.',
      'Because it’s tucked away in SEC filings, tangled in legal jargon… or buried under whatever headline the media wants you to focus on.',
      'That’s what I built my “Legal Inside Tip,” <strong>LIT</strong>.',
      '<strong>LIT</strong> shuts out all the noise from the legacy media and taps into factors which determine quality inside trades.',
      'You could wake up every morning feeling like you have an edge in the market.',
      `<p>${cta('And if you take this step today…')}</p>`,
      'You could end up getting enough freedom to finally stop worrying about the market, the economy, or what the media says is coming next.',
      'It’s all in your hands now… {{FIRSTNAME}}',
      `<p>${cta('Get access to LIT right here')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
  {
    id: 'w7',
    offsetMinutes: 6 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'Congress might finally lose its biggest money cheat code' },
      { subject: 'Why Pelosi’s portfolio could go dark forever' },
      { subject: 'This bill targets Congress’ biggest stock market edge.' },
      { subject: 'The PELOSI Act could end the game' },
      { subject: 'If this passes, Congress would have no edge in the stock market anymore' },
      { subject: 'Have you heard about the PELOSI Act?' },
    ],
    body: [
      '<p><strong>Hello {{FIRSTNAME}},</strong></p>',
      'Congress might finally be forced to stop treating the stock market like a personal ATM…',
      'The PELOSI Act is back on the table.',
      'Reintroduced by Senator Josh Hawley (R - Missouri)...',
      'It would ban lawmakers and their spouses from trading stocks while in office…',
      'And yes, it’s named after Nancy Pelosi, who’s racked up a 685% return since 2014…',
      `<p>Compare that to the S&P 500’s 193% return in the same period and you’ll agree with me that ${cta('the everyday Joe needs an edge.')}</p>`,
      'While it\'s a good bill, with President Trump and both sides of the aisle backing it,',
      'It could stall or have a loophole when it passes…',
      'And you can bet your bottom dollar they’ll keep cashing in while the rest of the herd guess their way through the market.',
      'You could get to track what the insiders are doing legally and on time.',
      'And not just politicians, but CEOs, board members and big-money players.',
      'That’s how you spot overlooked opportunities…',
      'Like VitalHUb (Ticker: VHI). It listed at $1.50 with no revenue to speak of.',
      'Most investors never heard of it and some ignored it.',
      'But insiders kept buying…',
      'And when the dust settled, the stock soared to $12… a 700% return.',
      'Enough to turn a $10,000 stake into $80,000.',
      'Or consider Kulr Technologies Group (Ticker: Kulr)',
      'Kulr was hanging on by a thread… trading at just 28 cents and on the verge of being delisted',
      'They were running out of cash and most investors wouldn’t have touched it.',
      'But I saw something different…',
      'Behind the scenes,',
      'This company had built a powerhouse team of former military leaders…',
      'And owned critical patents for a little-known energy technology built for the military.',
      'And as geopolitical tensions flared,',
      'I knew this tech would suddenly become important to national security.',
      'In September 2024...',
      'I sent an email to a small group of individual investors with just one line:',
      quote('“I’ve been looking into a small company trading on the NYSE… ticker symbol KLUR… this is seriously undervalued.”'),
      'Sure enough, within weeks, KULR shot up to $5.49.',
      'That’s a 19.6x gain… which could have turned a $10,000 investment into $196,000.',
      'Or SilverCrest Metals (Ticker: SILV)',
      'Another overlooked stock, most mainstream outlets never talked about it… until it went for a 2,063% run.',
      'Enough to turn a $10,000 stake into more than $206,300.',
      'Look, I could go on and on.',
      'But all I want you to take from me today is…',
      `<p>${cta('If you follow the money the right way,')} you’ll do better than 99% of regular Americans.</p>`,
      'And in the process, you will be better prepared for retirement.',
      'And while I can’t guarantee you a perfect trading system…',
      'You could stop playing defense with your finances…',
      'So whether Congress passes the PELOSI Act or not,',
      'You could ride the profit wave with people making the real moves.',
      `<p>${cta('Click here to see how you could follow the money')}</p>`,
      '__SIGNOFF__',
    ],
  },
  {
    id: 'w8',
    offsetMinutes: 7 * D,
    brand: 'INSIDER BUYING',
    signoffTitle: SIGNOFF_BUYING,
    subjects: [
      { subject: 'The answers to your questions {{FIRSTNAME}}…' },
      { subject: 'Have you seen these answers {{FIRSTNAME}}?' },
      { subject: 'Let’s talk about these questions {{FIRSTNAME}}' },
      { subject: 'What you might want to know before you catch your first winner' },
      { subject: 'Before you act… read these answers' },
    ],
    body: [
      'Hello {{FIRSTNAME}},',
      'I know you’ve got questions. Honestly, I’d be surprised if you didn’t.',
      'It’s always great to get the full picture… and I respect that. So let’s walk through them together…',
      '<p><strong>Q: Is this newsletter/Insider Buying legal?</strong></p>',
      '<p><strong>Me:</strong> Yes. When corporate insiders (CEOs, CFOs, directors) buy stock, they must file it with the SEC… It’s public info. LIT helps track it faster and smarter.</p>',
      '<p><strong>Q: How sure are you anyone can profit from legal insider buying?</strong></p>',
      'Me: Anyone can. A report from Harvard confirms Insider buying beats the stock market by double digits on average annually.',
      'Legendary Investor Peter Lynch added,',
      quote('“Insiders might sell their stock for any number of reasons, but they buy them for only one: they think the price will rise.”'),
      'And anyone who followed the right insider moves could have earned…',
      '<p><strong>1382% returns on Kulr Technologies Group (Ticker: KULR)...</strong></p>',
      '2,063% returns on SilverCrest Metals (Ticker: SILV)...',
      '<p><strong>And 2847% on Emerita Resources (Ticker: EMO)</strong></p>',
      `<p>But it’s important you follow the <strong>right</strong> insider trades. ${cta('Here’s how you could start today.')}</p>`,
      '<p><strong>Q: Won’t I just hear about these trades in the news?</strong><br>Me: Not until it’s too late. We alert you before the media even thinks about reporting on it.</p>',
      '<p><strong>Q: Why can’t I just use other sources to follow politicians and insiders?</strong></p>',
      'Me: You could. But here, I don’t throw insider data at you, I show you when and how to act. Not every insider trade is worth following.',
      'You need the right entry and exit so you lock in profits.',
      '<p><strong>Q: If LIT and this service are so good, why are you giving it to me?</strong></p>',
      '<p><strong>Me:</strong> Insider buying guides every investing decision I make, this is what I’m doing with my money.</p>',
      'I know what it’s like to work hard, put money into the market, and end up on the wrong side of the trade. Like I said earlier, that’s exactly why I started this movement.',
      'So you and I can stop being the “exit liquidity” for the elites.',
      'But it’s important you know there’s no perfect or black box system. You shouldn\'t invest more than you are willing to lose',
      '<p><strong>Q: Insiders can be wrong, right?</strong><br>Me: Yes</p>',
      'But when many insiders from the same company buy big… that’s when odds swing in your favor.',
      'LIT also considers the frequency of buys, the buy size relative to the market cap of the company, the seniority of insiders buying, and the increase in holdings of insiders.',
      'That way, we’re focused on the insider moves.',
      '<p><strong>Q: What about Insider Selling? Do you consider it?</strong></p>',
      'Me: Insider selling is another great means of deciding whether to invest stock or not.',
      'If many insiders are dumping shares at an alarming rate, that tells you to stay far away from that stock.',
      'While this movement is focused on insider buying, if there’s a great opportunity with selling… I’ll make sure it lands in your inbox.',
      '<p><strong>Q: What if I’m too late for any move?</strong><br>Me: That’s a fair question. Here’s the thing... quality insider buying, the kind LIT scans for, rarely signals a one-day spike.</p>',
      'LIT scans for stocks based on the conditions mentioned above and tells you if a stock is a worthy investment in the long term, you’re not chasing old trades.',
      '<p><strong>Q: What if I miss an alert?</strong><br>A: You’ll get email and SMS alerts. Then we’ll follow up with reminders to make sure you don’t miss out.</p>',
      '<p><strong>Q: How fast can I make money?</strong><br>Me: First, I can’t guarantee you 100% wins. Investing always takes risks…</p>',
      'That said, some plays take days or weeks. Others move in months. It’s not fixed.',
      '<p><strong>Q: Do I need to be a financial expert to use this service?</strong></p>',
      '<p><strong>Me:</strong> Not at all. You can be a part of this movement even if you’ve never traded in the stock market before.</p>',
      'And my stock alerts are easy to understand and act on in your brokerage account.',
      '<p><strong>Q: How much do I need to invest?</strong><br>Me: That’s up to you. Even a small position in the right trade can go a long way.</p>',
      'The stock Trump’s policies are backing is trading at less than $15 right now. So whether it’s $500 or $50,000…',
      `<p>You’re on the right track as long as you don’t invest more than you can afford to lose. ${cta('Here’s how you can gain access')}</p>`,
      `<p><strong>Q: What do I have to do so I don’t miss out on this stock’s potential profit ride?</strong><br>${cta('It’s simple, here’s your way in')}</p>`,
      'Now, here’s what I want you to do right now,',
      'Picture your perfect life. Imagine spending more time with your wife, kids and grandkids on dream vacations.',
      'If you had freedom, would you get a new home or just sleep well at night?',
      'Whatever your perfect life is, I could help you achieve your goals.',
      `<p>${cta('Again… here’s your way in.')}</p>`,
      'See you on the inside,',
      '__SIGNOFF__',
    ],
  },
];
