// Static reference quote data — used two ways:
//  1. As the metadata layer (name / sector / market cap) merged onto live
//     Yahoo v8 chart quotes, which don't carry market cap.
//  2. As the full fallback quote when Yahoo is unreachable, with a small
//     deterministic daily jitter applied so figures stay plausible.
// Values are rounded approximations refreshed manually; live prices always
// take precedence when the chart endpoint responds.

export interface ReferenceQuote {
  name: string;
  sector: string;
  price: number;
  marketCap: number;
  avgVolume: number;
}

const B = 1e9;
const M = 1e6;

export const REFERENCE_QUOTES: Record<string, ReferenceQuote> = {
  // ───── Mega caps / blue chips ─────
  AAPL: { name: 'Apple Inc.', sector: 'Technology', price: 290.5, marketCap: 4_300 * B, avgVolume: 52 * M },
  MSFT: { name: 'Microsoft', sector: 'Technology', price: 512.4, marketCap: 3_810 * B, avgVolume: 21 * M },
  NVDA: { name: 'NVIDIA', sector: 'Technology', price: 176.3, marketCap: 4_280 * B, avgVolume: 215 * M },
  AMZN: { name: 'Amazon.com', sector: 'Consumer Discretionary', price: 228.6, marketCap: 2_420 * B, avgVolume: 41 * M },
  GOOGL: { name: 'Alphabet (Class A)', sector: 'Communication Services', price: 196.2, marketCap: 2_380 * B, avgVolume: 28 * M },
  GOOG: { name: 'Alphabet (Class C)', sector: 'Communication Services', price: 197.8, marketCap: 2_380 * B, avgVolume: 22 * M },
  META: { name: 'Meta Platforms', sector: 'Communication Services', price: 718.4, marketCap: 1_810 * B, avgVolume: 13 * M },
  TSLA: { name: 'Tesla', sector: 'Consumer Discretionary', price: 338.2, marketCap: 1_090 * B, avgVolume: 92 * M },
  AVGO: { name: 'Broadcom', sector: 'Technology', price: 251.7, marketCap: 1_180 * B, avgVolume: 24 * M },
  'BRK-B': { name: 'Berkshire Hathaway (B)', sector: 'Financial Services', price: 487.3, marketCap: 1_050 * B, avgVolume: 3.8 * M },
  JPM: { name: 'JPMorgan Chase', sector: 'Financial Services', price: 266.1, marketCap: 745 * B, avgVolume: 8.6 * M },
  V: { name: 'Visa Inc.', sector: 'Financial Services', price: 336.4, marketCap: 645 * B, avgVolume: 6.5 * M },
  MA: { name: 'Mastercard', sector: 'Financial Services', price: 562.8, marketCap: 512 * B, avgVolume: 2.6 * M },
  UNH: { name: 'UnitedHealth Group', sector: 'Healthcare', price: 531.6, marketCap: 482 * B, avgVolume: 3.4 * M },
  XOM: { name: 'Exxon Mobil', sector: 'Energy', price: 116.2, marketCap: 502 * B, avgVolume: 15 * M },
  JNJ: { name: 'Johnson & Johnson', sector: 'Healthcare', price: 156.4, marketCap: 376 * B, avgVolume: 7.8 * M },
  WMT: { name: 'Walmart', sector: 'Consumer Staples', price: 103.1, marketCap: 825 * B, avgVolume: 17 * M },
  PG: { name: 'Procter & Gamble', sector: 'Consumer Staples', price: 168.9, marketCap: 396 * B, avgVolume: 6.4 * M },
  HD: { name: 'Home Depot', sector: 'Consumer Discretionary', price: 396.5, marketCap: 392 * B, avgVolume: 3.2 * M },
  COST: { name: 'Costco Wholesale', sector: 'Consumer Staples', price: 982.4, marketCap: 436 * B, avgVolume: 1.9 * M },
  ORCL: { name: 'Oracle', sector: 'Technology', price: 176.8, marketCap: 492 * B, avgVolume: 9.2 * M },
  LLY: { name: 'Eli Lilly', sector: 'Healthcare', price: 822.6, marketCap: 742 * B, avgVolume: 2.8 * M },
  ABBV: { name: 'AbbVie', sector: 'Healthcare', price: 196.3, marketCap: 346 * B, avgVolume: 5.6 * M },
  BAC: { name: 'Bank of America', sector: 'Financial Services', price: 47.4, marketCap: 362 * B, avgVolume: 36 * M },
  KO: { name: 'Coca-Cola', sector: 'Consumer Staples', price: 68.2, marketCap: 294 * B, avgVolume: 13 * M },
  PEP: { name: 'PepsiCo', sector: 'Consumer Staples', price: 171.6, marketCap: 236 * B, avgVolume: 5.1 * M },
  MRK: { name: 'Merck & Co.', sector: 'Healthcare', price: 106.4, marketCap: 268 * B, avgVolume: 9.8 * M },
  CVX: { name: 'Chevron', sector: 'Energy', price: 158.7, marketCap: 282 * B, avgVolume: 7.2 * M },
  CRM: { name: 'Salesforce', sector: 'Technology', price: 281.5, marketCap: 271 * B, avgVolume: 5.4 * M },
  ADBE: { name: 'Adobe', sector: 'Technology', price: 482.1, marketCap: 211 * B, avgVolume: 2.9 * M },
  NFLX: { name: 'Netflix', sector: 'Communication Services', price: 1192.3, marketCap: 508 * B, avgVolume: 2.4 * M },
  AMD: { name: 'Advanced Micro Devices', sector: 'Technology', price: 176.2, marketCap: 286 * B, avgVolume: 46 * M },
  CSCO: { name: 'Cisco Systems', sector: 'Technology', price: 62.6, marketCap: 246 * B, avgVolume: 17 * M },
  MCD: { name: "McDonald's", sector: 'Consumer Discretionary', price: 304.8, marketCap: 218 * B, avgVolume: 2.6 * M },
  ABT: { name: 'Abbott Laboratories', sector: 'Healthcare', price: 126.1, marketCap: 218 * B, avgVolume: 5.2 * M },
  LIN: { name: 'Linde plc', sector: 'Materials', price: 471.2, marketCap: 224 * B, avgVolume: 1.5 * M },
  DIS: { name: 'Walt Disney', sector: 'Communication Services', price: 112.6, marketCap: 204 * B, avgVolume: 8.4 * M },
  WFC: { name: 'Wells Fargo', sector: 'Financial Services', price: 75.8, marketCap: 248 * B, avgVolume: 14 * M },
  GS: { name: 'Goldman Sachs', sector: 'Financial Services', price: 592.4, marketCap: 186 * B, avgVolume: 1.9 * M },
  MS: { name: 'Morgan Stanley', sector: 'Financial Services', price: 126.3, marketCap: 202 * B, avgVolume: 5.8 * M },
  AXP: { name: 'American Express', sector: 'Financial Services', price: 291.2, marketCap: 206 * B, avgVolume: 2.4 * M },
  IBM: { name: 'IBM', sector: 'Technology', price: 246.8, marketCap: 226 * B, avgVolume: 3.8 * M },
  CAT: { name: 'Caterpillar', sector: 'Industrials', price: 381.4, marketCap: 184 * B, avgVolume: 2.2 * M },
  VZ: { name: 'Verizon Communications', sector: 'Communication Services', price: 43.2, marketCap: 182 * B, avgVolume: 19 * M },
  T: { name: 'AT&T', sector: 'Communication Services', price: 23.4, marketCap: 168 * B, avgVolume: 32 * M },
  PM: { name: 'Philip Morris Intl', sector: 'Consumer Staples', price: 136.2, marketCap: 212 * B, avgVolume: 4.6 * M },
  RTX: { name: 'RTX Corp.', sector: 'Industrials', price: 131.4, marketCap: 175 * B, avgVolume: 5.2 * M },
  HON: { name: 'Honeywell', sector: 'Industrials', price: 226.3, marketCap: 146 * B, avgVolume: 2.8 * M },
  QCOM: { name: 'Qualcomm', sector: 'Technology', price: 176.4, marketCap: 194 * B, avgVolume: 7.4 * M },
  TXN: { name: 'Texas Instruments', sector: 'Technology', price: 196.2, marketCap: 178 * B, avgVolume: 4.6 * M },
  INTU: { name: 'Intuit', sector: 'Technology', price: 682.4, marketCap: 191 * B, avgVolume: 1.4 * M },
  AMGN: { name: 'Amgen', sector: 'Healthcare', price: 312.6, marketCap: 168 * B, avgVolume: 2.4 * M },
  NEE: { name: 'NextEra Energy', sector: 'Utilities', price: 78.4, marketCap: 161 * B, avgVolume: 9.6 * M },
  UNP: { name: 'Union Pacific', sector: 'Industrials', price: 246.2, marketCap: 148 * B, avgVolume: 2.6 * M },
  LOW: { name: "Lowe's Companies", sector: 'Consumer Discretionary', price: 256.4, marketCap: 144 * B, avgVolume: 2.1 * M },
  SPGI: { name: 'S&P Global', sector: 'Financial Services', price: 521.6, marketCap: 162 * B, avgVolume: 1.2 * M },
  BLK: { name: 'BlackRock', sector: 'Financial Services', price: 1024.3, marketCap: 158 * B, avgVolume: 0.6 * M },
  C: { name: 'Citigroup', sector: 'Financial Services', price: 78.6, marketCap: 148 * B, avgVolume: 12 * M },
  SCHW: { name: 'Charles Schwab', sector: 'Financial Services', price: 78.9, marketCap: 142 * B, avgVolume: 7.8 * M },
  BA: { name: 'Boeing', sector: 'Industrials', price: 186.2, marketCap: 140 * B, avgVolume: 6.8 * M },
  PFE: { name: 'Pfizer', sector: 'Healthcare', price: 26.8, marketCap: 152 * B, avgVolume: 34 * M },
  INTC: { name: 'Intel', sector: 'Technology', price: 23.4, marketCap: 101 * B, avgVolume: 58 * M },
  NKE: { name: 'Nike', sector: 'Consumer Discretionary', price: 75.6, marketCap: 112 * B, avgVolume: 9.2 * M },
  TGT: { name: 'Target', sector: 'Consumer Staples', price: 131.2, marketCap: 60 * B, avgVolume: 4.2 * M },
  CVS: { name: 'CVS Health', sector: 'Healthcare', price: 64.8, marketCap: 81 * B, avgVolume: 8.2 * M },
  F: { name: 'Ford Motor', sector: 'Consumer Discretionary', price: 11.2, marketCap: 44 * B, avgVolume: 48 * M },
  GM: { name: 'General Motors', sector: 'Consumer Discretionary', price: 52.4, marketCap: 57 * B, avgVolume: 9.4 * M },
  UBER: { name: 'Uber Technologies', sector: 'Industrials', price: 86.2, marketCap: 179 * B, avgVolume: 14 * M },
  PLTR: { name: 'Palantir Technologies', sector: 'Technology', price: 92.4, marketCap: 208 * B, avgVolume: 88 * M },
  COIN: { name: 'Coinbase Global', sector: 'Financial Services', price: 321.6, marketCap: 81 * B, avgVolume: 9.1 * M },
  MSTR: { name: 'MicroStrategy', sector: 'Technology', price: 421.4, marketCap: 74 * B, avgVolume: 7.4 * M },
  SMCI: { name: 'Super Micro Computer', sector: 'Technology', price: 46.2, marketCap: 27 * B, avgVolume: 32 * M },
  CRWD: { name: 'CrowdStrike Holdings', sector: 'Technology', price: 432.6, marketCap: 106 * B, avgVolume: 2.8 * M },
  MRNA: { name: 'Moderna', sector: 'Healthcare', price: 44.6, marketCap: 17 * B, avgVolume: 9.6 * M },
  LULU: { name: 'Lululemon Athletica', sector: 'Consumer Discretionary', price: 281.4, marketCap: 33 * B, avgVolume: 2.2 * M },
  WBA: { name: 'Walgreens Boots Alliance', sector: 'Healthcare', price: 11.2, marketCap: 9.7 * B, avgVolume: 18 * M },
  BBY: { name: 'Best Buy', sector: 'Consumer Discretionary', price: 78.2, marketCap: 16.5 * B, avgVolume: 2.8 * M },
  DJT: { name: 'Trump Media & Technology', sector: 'Communication Services', price: 28.4, marketCap: 5.6 * B, avgVolume: 8.4 * M },
  ABNB: { name: 'Airbnb', sector: 'Consumer Discretionary', price: 141.2, marketCap: 88 * B, avgVolume: 4.2 * M },
  KHC: { name: 'Kraft Heinz', sector: 'Consumer Staples', price: 31.6, marketCap: 38 * B, avgVolume: 7.8 * M },
  MCO: { name: "Moody's Corp.", sector: 'Financial Services', price: 482.6, marketCap: 87 * B, avgVolume: 0.8 * M },
  DVA: { name: 'DaVita', sector: 'Healthcare', price: 146.2, marketCap: 12 * B, avgVolume: 0.9 * M },
  OXY: { name: 'Occidental Petroleum', sector: 'Energy', price: 52.6, marketCap: 49 * B, avgVolume: 11 * M },
  LMT: { name: 'Lockheed Martin', sector: 'Industrials', price: 476.2, marketCap: 112 * B, avgVolume: 1.2 * M },
  GD: { name: 'General Dynamics', sector: 'Industrials', price: 296.4, marketCap: 80 * B, avgVolume: 1.1 * M },
  NOC: { name: 'Northrop Grumman', sector: 'Industrials', price: 486.2, marketCap: 70 * B, avgVolume: 0.8 * M },
  MO: { name: 'Altria Group', sector: 'Consumer Staples', price: 55.4, marketCap: 94 * B, avgVolume: 8.6 * M },
  TMUS: { name: 'T-Mobile US', sector: 'Communication Services', price: 236.4, marketCap: 268 * B, avgVolume: 3.6 * M },
  MU: { name: 'Micron Technology', sector: 'Technology', price: 126.4, marketCap: 140 * B, avgVolume: 21 * M },

  // ───── Buffett / value names ─────
  VRSN: { name: 'VeriSign', sector: 'Technology', price: 271.2, marketCap: 26 * B, avgVolume: 0.7 * M },
  COF: { name: 'Capital One Financial', sector: 'Financial Services', price: 196.4, marketCap: 75 * B, avgVolume: 2.6 * M },
  KR: { name: 'Kroger', sector: 'Consumer Staples', price: 62.4, marketCap: 45 * B, avgVolume: 5.8 * M },
  SIRI: { name: 'Sirius XM Holdings', sector: 'Communication Services', price: 23.2, marketCap: 8.5 * B, avgVolume: 3.4 * M },
  NU: { name: 'Nu Holdings', sector: 'Financial Services', price: 13.1, marketCap: 62 * B, avgVolume: 38 * M },
  CB: { name: 'Chubb Limited', sector: 'Financial Services', price: 286.2, marketCap: 115 * B, avgVolume: 1.4 * M },
  AON: { name: 'Aon plc', sector: 'Financial Services', price: 366.4, marketCap: 78 * B, avgVolume: 0.9 * M },
  ALLY: { name: 'Ally Financial', sector: 'Financial Services', price: 38.2, marketCap: 11.5 * B, avgVolume: 3.2 * M },
  LPX: { name: 'Louisiana-Pacific', sector: 'Materials', price: 95.4, marketCap: 6.7 * B, avgVolume: 0.8 * M },
  DPZ: { name: "Domino's Pizza", sector: 'Consumer Discretionary', price: 472.6, marketCap: 16 * B, avgVolume: 0.6 * M },

  // ───── Bezos Expeditions–linked ─────
  RIVN: { name: 'Rivian Automotive', sector: 'Consumer Discretionary', price: 14.2, marketCap: 15 * B, avgVolume: 24 * M },
  WDAY: { name: 'Workday', sector: 'Technology', price: 256.4, marketCap: 68 * B, avgVolume: 1.8 * M },
  TWLO: { name: 'Twilio', sector: 'Technology', price: 106.2, marketCap: 16 * B, avgVolume: 2.4 * M },
  GRAL: { name: 'GRAIL Inc.', sector: 'Healthcare', price: 45.2, marketCap: 1.6 * B, avgVolume: 0.4 * M },
  DOMO: { name: 'Domo Inc.', sector: 'Technology', price: 9.4, marketCap: 0.36 * B, avgVolume: 0.5 * M },

  // ───── ETFs / funds (Dalio book) ─────
  IVV: { name: 'iShares Core S&P 500 ETF', sector: 'Diversified', price: 612.4, marketCap: 560 * B, avgVolume: 4.6 * M },
  IEMG: { name: 'iShares Core MSCI EM ETF', sector: 'Diversified', price: 62.4, marketCap: 85 * B, avgVolume: 11 * M },
  SPY: { name: 'SPDR S&P 500 ETF', sector: 'Diversified', price: 607.2, marketCap: 620 * B, avgVolume: 48 * M },
  GLD: { name: 'SPDR Gold Shares', sector: 'Commodities', price: 312.4, marketCap: 110 * B, avgVolume: 8.2 * M },
  TLT: { name: 'iShares 20+ Yr Treasury ETF', sector: 'Fixed Income', price: 88.6, marketCap: 48 * B, avgVolume: 32 * M },

  // ───── Gold miners ─────
  NEM: { name: 'Newmont Corp.', sector: 'Materials — Gold', price: 58.4, marketCap: 65 * B, avgVolume: 8.4 * M },
  GOLD: { name: 'Barrick Gold', sector: 'Materials — Gold', price: 21.2, marketCap: 37 * B, avgVolume: 18 * M },
  AEM: { name: 'Agnico Eagle Mines', sector: 'Materials — Gold', price: 118.6, marketCap: 60 * B, avgVolume: 2.8 * M },
  KGC: { name: 'Kinross Gold', sector: 'Materials — Gold', price: 12.4, marketCap: 15 * B, avgVolume: 14 * M },
  FNV: { name: 'Franco-Nevada', sector: 'Materials — Gold', price: 156.2, marketCap: 30 * B, avgVolume: 0.7 * M },
  WPM: { name: 'Wheaton Precious Metals', sector: 'Materials — Gold & Silver', price: 76.4, marketCap: 34 * B, avgVolume: 2.1 * M },
  RGLD: { name: 'Royal Gold', sector: 'Materials — Gold', price: 166.2, marketCap: 11 * B, avgVolume: 0.5 * M },
  AU: { name: 'AngloGold Ashanti', sector: 'Materials — Gold', price: 38.6, marketCap: 16 * B, avgVolume: 3.2 * M },
  GFI: { name: 'Gold Fields', sector: 'Materials — Gold', price: 22.4, marketCap: 20 * B, avgVolume: 4.8 * M },
  HMY: { name: 'Harmony Gold Mining', sector: 'Materials — Gold', price: 14.2, marketCap: 9 * B, avgVolume: 3.4 * M },
  EGO: { name: 'Eldorado Gold', sector: 'Materials — Gold', price: 18.4, marketCap: 3.7 * B, avgVolume: 2.2 * M },
  BTG: { name: 'B2Gold', sector: 'Materials — Gold', price: 3.3, marketCap: 4.2 * B, avgVolume: 16 * M },
  AGI: { name: 'Alamos Gold', sector: 'Materials — Gold', price: 24.6, marketCap: 10 * B, avgVolume: 3.1 * M },
  OR: { name: 'Osisko Gold Royalties', sector: 'Materials — Gold', price: 23.4, marketCap: 4.3 * B, avgVolume: 1.1 * M },
  SSRM: { name: 'SSR Mining', sector: 'Materials — Gold & Silver', price: 11.2, marketCap: 2.2 * B, avgVolume: 2.6 * M },
  CDE: { name: 'Coeur Mining', sector: 'Materials — Gold & Silver', price: 7.1, marketCap: 2.8 * B, avgVolume: 9.4 * M },
  IAG: { name: 'IAMGOLD', sector: 'Materials — Gold', price: 6.6, marketCap: 3.7 * B, avgVolume: 5.6 * M },
  NGD: { name: 'New Gold', sector: 'Materials — Gold', price: 3.4, marketCap: 2.3 * B, avgVolume: 8.2 * M },
  SAND: { name: 'Sandstorm Gold', sector: 'Materials — Gold', price: 6.9, marketCap: 2 * B, avgVolume: 3.4 * M },
  EQX: { name: 'Equinox Gold', sector: 'Materials — Gold', price: 7.2, marketCap: 2.4 * B, avgVolume: 4.2 * M },
  DRD: { name: 'DRDGOLD', sector: 'Materials — Gold', price: 14.4, marketCap: 1.2 * B, avgVolume: 0.6 * M },
  NG: { name: 'NovaGold Resources', sector: 'Materials — Gold', price: 4.6, marketCap: 1.5 * B, avgVolume: 2.4 * M },
  GORO: { name: 'Gold Resource Corp.', sector: 'Materials — Gold', price: 0.56, marketCap: 0.05 * B, avgVolume: 0.6 * M },
  USAU: { name: 'U.S. Gold Corp.', sector: 'Materials — Gold', price: 8.6, marketCap: 0.1 * B, avgVolume: 0.2 * M },

  // ───── Silver miners / funds ─────
  PAAS: { name: 'Pan American Silver', sector: 'Materials — Silver', price: 24.2, marketCap: 8.7 * B, avgVolume: 3.8 * M },
  AG: { name: 'First Majestic Silver', sector: 'Materials — Silver', price: 8.3, marketCap: 2.4 * B, avgVolume: 8.6 * M },
  HL: { name: 'Hecla Mining', sector: 'Materials — Silver', price: 6.5, marketCap: 4 * B, avgVolume: 9.2 * M },
  EXK: { name: 'Endeavour Silver', sector: 'Materials — Silver', price: 4.7, marketCap: 1.1 * B, avgVolume: 4.6 * M },
  FSM: { name: 'Fortuna Mining', sector: 'Materials — Silver', price: 5.9, marketCap: 1.8 * B, avgVolume: 4.4 * M },
  MAG: { name: 'MAG Silver', sector: 'Materials — Silver', price: 14.2, marketCap: 1.4 * B, avgVolume: 1.2 * M },
  SVM: { name: 'Silvercorp Metals', sector: 'Materials — Silver', price: 4.3, marketCap: 0.75 * B, avgVolume: 1.6 * M },
  ASM: { name: 'Avino Silver & Gold', sector: 'Materials — Silver', price: 1.9, marketCap: 0.35 * B, avgVolume: 1.4 * M },
  GATO: { name: 'Gatos Silver', sector: 'Materials — Silver', price: 17.2, marketCap: 1.2 * B, avgVolume: 0.8 * M },
  SILV: { name: 'SilverCrest Metals', sector: 'Materials — Silver', price: 3.9, marketCap: 0.6 * B, avgVolume: 1.8 * M },
  USAS: { name: 'Americas Gold & Silver', sector: 'Materials — Silver', price: 12.1, marketCap: 0.25 * B, avgVolume: 0.4 * M },
  BVN: { name: 'Buenaventura Mining', sector: 'Materials — Silver', price: 16.4, marketCap: 4 * B, avgVolume: 1.2 * M },
  SLV: { name: 'iShares Silver Trust', sector: 'Commodities — Silver', price: 28.6, marketCap: 13 * B, avgVolume: 22 * M },
  SIVR: { name: 'abrdn Physical Silver ETF', sector: 'Commodities — Silver', price: 29.4, marketCap: 1.5 * B, avgVolume: 0.6 * M },
  PSLV: { name: 'Sprott Physical Silver Trust', sector: 'Commodities — Silver', price: 10.6, marketCap: 5 * B, avgVolume: 4.2 * M },
  SIL: { name: 'Global X Silver Miners ETF', sector: 'Commodities — Silver', price: 42.6, marketCap: 1.4 * B, avgVolume: 0.4 * M },
  SILJ: { name: 'Amplify Junior Silver ETF', sector: 'Commodities — Silver', price: 12.6, marketCap: 0.9 * B, avgVolume: 1.6 * M },

  // ───── Metals & mining ─────
  BHP: { name: 'BHP Group', sector: 'Materials — Metals & Mining', price: 62.4, marketCap: 155 * B, avgVolume: 3.4 * M },
  RIO: { name: 'Rio Tinto', sector: 'Materials — Metals & Mining', price: 68.2, marketCap: 110 * B, avgVolume: 2.8 * M },
  VALE: { name: 'Vale S.A.', sector: 'Materials — Metals & Mining', price: 11.4, marketCap: 48 * B, avgVolume: 26 * M },
  FCX: { name: 'Freeport-McMoRan', sector: 'Materials — Copper', price: 48.6, marketCap: 68 * B, avgVolume: 12 * M },
  SCCO: { name: 'Southern Copper', sector: 'Materials — Copper', price: 106.4, marketCap: 82 * B, avgVolume: 1.1 * M },
  NUE: { name: 'Nucor', sector: 'Materials — Steel', price: 166.2, marketCap: 38 * B, avgVolume: 1.6 * M },
  STLD: { name: 'Steel Dynamics', sector: 'Materials — Steel', price: 136.4, marketCap: 20 * B, avgVolume: 1.4 * M },
  CLF: { name: 'Cleveland-Cliffs', sector: 'Materials — Steel', price: 12.2, marketCap: 6 * B, avgVolume: 14 * M },
  X: { name: 'United States Steel', sector: 'Materials — Steel', price: 38.4, marketCap: 9 * B, avgVolume: 6.2 * M },
  AA: { name: 'Alcoa', sector: 'Materials — Aluminum', price: 38.6, marketCap: 9.8 * B, avgVolume: 5.4 * M },
  CENX: { name: 'Century Aluminum', sector: 'Materials — Aluminum', price: 18.2, marketCap: 1.7 * B, avgVolume: 1.8 * M },
  MP: { name: 'MP Materials', sector: 'Materials — Rare Earth', price: 22.6, marketCap: 3.6 * B, avgVolume: 3.2 * M },
  ALB: { name: 'Albemarle', sector: 'Materials — Lithium', price: 96.2, marketCap: 11 * B, avgVolume: 2.4 * M },
  SQM: { name: 'Sociedad Química y Minera', sector: 'Materials — Lithium', price: 42.4, marketCap: 12 * B, avgVolume: 1.4 * M },
  TECK: { name: 'Teck Resources', sector: 'Materials — Metals & Mining', price: 48.2, marketCap: 25 * B, avgVolume: 2.8 * M },
  HBM: { name: 'Hudbay Minerals', sector: 'Materials — Copper', price: 9.6, marketCap: 3.7 * B, avgVolume: 3.4 * M },
  ERO: { name: 'Ero Copper', sector: 'Materials — Copper', price: 17.2, marketCap: 1.8 * B, avgVolume: 0.7 * M },
  CMC: { name: 'Commercial Metals', sector: 'Materials — Steel', price: 58.4, marketCap: 6.6 * B, avgVolume: 0.9 * M },
  RS: { name: 'Reliance Inc.', sector: 'Materials — Steel', price: 296.4, marketCap: 17 * B, avgVolume: 0.4 * M },
  ATI: { name: 'ATI Inc.', sector: 'Materials — Specialty Metals', price: 58.6, marketCap: 8.3 * B, avgVolume: 1.2 * M },
  MT: { name: 'ArcelorMittal', sector: 'Materials — Steel', price: 28.4, marketCap: 22 * B, avgVolume: 2.6 * M },
  GGB: { name: 'Gerdau S.A.', sector: 'Materials — Steel', price: 3.3, marketCap: 6.8 * B, avgVolume: 6.4 * M },
  SID: { name: 'Companhia Siderúrgica', sector: 'Materials — Steel', price: 2.5, marketCap: 3.3 * B, avgVolume: 2.8 * M },

  // ───── Oil & energy ─────
  COP: { name: 'ConocoPhillips', sector: 'Energy — Oil & Gas', price: 106.2, marketCap: 131 * B, avgVolume: 6.4 * M },
  EOG: { name: 'EOG Resources', sector: 'Energy — Oil & Gas', price: 128.4, marketCap: 72 * B, avgVolume: 3.2 * M },
  SLB: { name: 'SLB (Schlumberger)', sector: 'Energy — Oilfield Services', price: 42.6, marketCap: 60 * B, avgVolume: 11 * M },
  PSX: { name: 'Phillips 66', sector: 'Energy — Refining', price: 136.2, marketCap: 56 * B, avgVolume: 2.4 * M },
  VLO: { name: 'Valero Energy', sector: 'Energy — Refining', price: 146.4, marketCap: 46 * B, avgVolume: 2.6 * M },
  MPC: { name: 'Marathon Petroleum', sector: 'Energy — Refining', price: 176.2, marketCap: 62 * B, avgVolume: 2.2 * M },
  HES: { name: 'Hess Corp.', sector: 'Energy — Oil & Gas', price: 148.6, marketCap: 45 * B, avgVolume: 2.8 * M },
  WMB: { name: 'Williams Companies', sector: 'Energy — Midstream', price: 58.4, marketCap: 70 * B, avgVolume: 6.2 * M },
  KMI: { name: 'Kinder Morgan', sector: 'Energy — Midstream', price: 27.2, marketCap: 60 * B, avgVolume: 12 * M },
  OKE: { name: 'ONEOK', sector: 'Energy — Midstream', price: 92.6, marketCap: 54 * B, avgVolume: 2.6 * M },
  HAL: { name: 'Halliburton', sector: 'Energy — Oilfield Services', price: 28.2, marketCap: 25 * B, avgVolume: 9.8 * M },
  BKR: { name: 'Baker Hughes', sector: 'Energy — Oilfield Services', price: 42.4, marketCap: 42 * B, avgVolume: 5.4 * M },
  DVN: { name: 'Devon Energy', sector: 'Energy — Oil & Gas', price: 42.2, marketCap: 27 * B, avgVolume: 7.6 * M },
  FANG: { name: 'Diamondback Energy', sector: 'Energy — Oil & Gas', price: 176.4, marketCap: 51 * B, avgVolume: 1.8 * M },
  CTRA: { name: 'Coterra Energy', sector: 'Energy — Oil & Gas', price: 26.2, marketCap: 19 * B, avgVolume: 7.2 * M },
  APA: { name: 'APA Corp.', sector: 'Energy — Oil & Gas', price: 22.4, marketCap: 8 * B, avgVolume: 6.4 * M },
  EQT: { name: 'EQT Corp.', sector: 'Energy — Natural Gas', price: 48.6, marketCap: 28 * B, avgVolume: 6.8 * M },
  AR: { name: 'Antero Resources', sector: 'Energy — Natural Gas', price: 35.2, marketCap: 11 * B, avgVolume: 3.6 * M },
  RRC: { name: 'Range Resources', sector: 'Energy — Natural Gas', price: 38.4, marketCap: 9 * B, avgVolume: 2.8 * M },
  PR: { name: 'Permian Resources', sector: 'Energy — Oil & Gas', price: 14.2, marketCap: 11 * B, avgVolume: 9.6 * M },
  SM: { name: 'SM Energy', sector: 'Energy — Oil & Gas', price: 42.6, marketCap: 4.8 * B, avgVolume: 1.8 * M },
  MUR: { name: 'Murphy Oil', sector: 'Energy — Oil & Gas', price: 28.4, marketCap: 4.2 * B, avgVolume: 2.2 * M },
  NOG: { name: 'Northern Oil & Gas', sector: 'Energy — Oil & Gas', price: 38.2, marketCap: 3.8 * B, avgVolume: 1.4 * M },
  CHRD: { name: 'Chord Energy', sector: 'Energy — Oil & Gas', price: 146.2, marketCap: 8.8 * B, avgVolume: 0.8 * M },

  // ───── Additional tech universe ─────
  NOW: { name: 'ServiceNow', sector: 'Technology', price: 952.4, marketCap: 196 * B, avgVolume: 1.4 * M },
  PANW: { name: 'Palo Alto Networks', sector: 'Technology', price: 196.2, marketCap: 131 * B, avgVolume: 4.8 * M },
  SNOW: { name: 'Snowflake', sector: 'Technology', price: 166.4, marketCap: 55 * B, avgVolume: 4.6 * M },
  AMAT: { name: 'Applied Materials', sector: 'Technology', price: 196.4, marketCap: 160 * B, avgVolume: 6.2 * M },
  LRCX: { name: 'Lam Research', sector: 'Technology', price: 96.2, marketCap: 123 * B, avgVolume: 12 * M },
  KLAC: { name: 'KLA Corp.', sector: 'Technology', price: 782.4, marketCap: 104 * B, avgVolume: 1.1 * M },
  ADI: { name: 'Analog Devices', sector: 'Technology', price: 236.2, marketCap: 117 * B, avgVolume: 2.8 * M },
  ANET: { name: 'Arista Networks', sector: 'Technology', price: 106.4, marketCap: 133 * B, avgVolume: 8.4 * M },
  DELL: { name: 'Dell Technologies', sector: 'Technology', price: 126.2, marketCap: 87 * B, avgVolume: 5.2 * M },
  HPQ: { name: 'HP Inc.', sector: 'Technology', price: 28.4, marketCap: 27 * B, avgVolume: 8.6 * M },
};
