/**
 * Right-sized cover images.
 *
 * Every card on the site used to request the FULL cover — a 1606px client
 * JPEG (~400 KB) or a 1200x700 Unsplash render (~94 KB) — into a slot 236-400
 * CSS px wide. Measured on the homepage 2026-09-11: 112 images, 5.7 MB. On a
 * normal connection that bandwidth is exactly what delays the next click
 * (George: "really slow and delayed when clicking on things"), because the
 * navigation's RSC fetch queues behind the pictures.
 *
 * This maps a cover URL to a `srcset` the browser can pick from:
 *   /editorial-thumbs/x.jpg  → w480/x.webp 480w, w960/x.webp 960w, x.jpg 1606w
 *   images.unsplash.com/...  → the same photo re-rendered at 480w and 960w
 * Anything else (a post's own /uploads image, a remote AI image) is returned
 * untouched — no srcset, no risk of pointing at a file that doesn't exist.
 *
 * Variants are generated by scripts/make-image-variants.mjs and listed in
 * thumb-variants.json; a cover missing from that list keeps serving its
 * original, so dropping a new JPEG in the folder can never 404 a card.
 */
import VARIANTS from "./thumb-variants.json";

/** How wide the image actually renders, so the browser downloads that size. */
export type CoverSize = "thumb" | "card" | "hero";

/** CSS width hints. `sizes` must describe the SLOT, not the image. */
const SIZES: Record<CoverSize, string> = {
  // Rail/list thumbnails: a small fixed box on desktop, a third of a phone.
  thumb: "(max-width: 768px) 33vw, 160px",
  // Grid cards: full width on a phone, roughly a third of the grid on desktop.
  card: "(max-width: 768px) 100vw, 420px",
  // Full-bleed heroes.
  hero: "(max-width: 1024px) 100vw, 1100px",
};

const THUMB_SET = new Set(VARIANTS as string[]);
const EDITORIAL = /^\/editorial-thumbs\/([^/]+)\.(jpe?g|png)$/i;

export interface CoverSources {
  src: string;
  srcSet?: string;
  sizes?: string;
}

export function coverSources(src: string, size: CoverSize = "card"): CoverSources {
  if (!src) return { src };

  const editorial = src.match(EDITORIAL);
  if (editorial) {
    const base = editorial[1];
    if (!THUMB_SET.has(base)) return { src };
    const w480 = `/editorial-thumbs/w480/${base}.webp`;
    const w960 = `/editorial-thumbs/w960/${base}.webp`;
    return {
      // Default for browsers without srcset support — never the 400 KB one.
      src: size === "thumb" ? w480 : w960,
      // The original stays in the candidate list for the hero, where a
      // 2x desktop viewport can genuinely use more than 960px.
      srcSet:
        size === "hero"
          ? `${w480} 480w, ${w960} 960w, ${src} 1606w`
          : `${w480} 480w, ${w960} 960w`,
      sizes: SIZES[size],
    };
  }

  // Unsplash renders any width on demand — ask for the one we display.
  if (src.startsWith("https://images.unsplash.com/")) {
    const original = new URL(src);
    const ow = Number(original.searchParams.get("w"));
    const oh = Number(original.searchParams.get("h"));
    // Keep the crop ratio the library asked for (1200x700 by default).
    const ratio = ow > 0 && oh > 0 ? oh / ow : 0;
    const at = (w: number) => {
      const u = new URL(src);
      u.searchParams.set("w", String(w));
      if (ratio) u.searchParams.set("h", String(Math.round(w * ratio)));
      return u.toString();
    };
    const small = at(480);
    const large = at(960);
    return {
      src: size === "thumb" ? small : large,
      srcSet: `${small} 480w, ${large} 960w${size === "hero" ? `, ${at(1600)} 1600w` : ""}`,
      sizes: SIZES[size],
    };
  }

  return { src };
}
